<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class TemplateCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            [
                'category_name' => 'Love & Romance Letters',
                'slug' => 'love-romance-letters',
                'icon' => 'love_icon.png',
                'image' => 'love_romance.jpg',
                'category_description' => 'Express your deepest emotions with our collection of love and romance letters.',
                'seo_description' => 'Explore heartfelt love letters, romance notes, and sweet messages for your special someone.',
                'status' => 1,
            ],
            [
                'category_name' => 'Holiday & Seasonal Letters',
                'slug' => 'holiday-seasonal-letters',
                'icon' => 'holiday_icon.png',
                'image' => 'holiday_seasonal.jpg',
                'category_description' => 'Celebrate the holidays with beautifully crafted seasonal letters.',
                'seo_description' => 'Find festive Christmas letters, Valentine’s Day cards, and more for every season.',
                'status' => 1,
            ],
            [
                'category_name' => 'Birthday & Special Occasion Letters',
                'slug' => 'birthday-special-occasion-letters',
                'icon' => 'birthday_icon.png',
                'image' => 'birthday_special_occasion.jpg',
                'category_description' => 'Make every special occasion memorable with personalized letters.',
                'seo_description' => 'Discover letters for birthdays, anniversaries, graduations, and more.',
                'status' => 1,
            ],
            [
                'category_name' => 'Just Because Letters',
                'slug' => 'just-because-letters',
                'icon' => 'just_because_icon.png',
                'image' => 'just_because.jpg',
                'category_description' => 'Surprise your loved ones with random acts of love and kindness.',
                'seo_description' => 'Send thoughtful letters just because you care.',
                'status' => 1,
            ],
            [
                'category_name' => 'Celebratory Letters',
                'slug' => 'celebratory-letters',
                'icon' => 'celebration_icon.png',
                'image' => 'celebratory.jpg',
                'category_description' => 'Celebrate life’s milestones with letters of joy and congratulations.',
                'seo_description' => 'Explore letters for engagements, achievements, and other celebratory moments.',
                'status' => 1,
            ],
            [
                'category_name' => 'Apology & Reconciliation Letters',
                'slug' => 'apology-reconciliation-letters',
                'icon' => 'apology_icon.png',
                'image' => 'apology_reconciliation.jpg',
                'category_description' => 'Mend relationships with sincere apologies and reconciliation letters.',
                'seo_description' => 'Find the right words to say you’re sorry and seek forgiveness.',
                'status' => 1,
            ],
            [
                'category_name' => 'Goodbye & Farewell Letters',
                'slug' => 'goodbye-farewell-letters',
                'icon' => 'goodbye_icon.png',
                'image' => 'goodbye_farewell.jpg',
                'category_description' => 'Say farewell with dignity and love through heartfelt letters.',
                'seo_description' => 'Send parting words and goodbye messages with grace.',
                'status' => 1,
            ],
            [
                'category_name' => 'Letters of Friendship',
                'slug' => 'letters-of-friendship',
                'icon' => 'friendship_icon.png',
                'image' => 'friendship.jpg',
                'category_description' => 'Strengthen bonds with letters dedicated to friendship.',
                'seo_description' => 'Celebrate your closest friends with thoughtful and heartfelt letters.',
                'status' => 1,
            ],
            [
                'category_name' => 'Inspirational & Motivational Letters',
                'slug' => 'inspirational-motivational-letters',
                'icon' => 'inspiration_icon.png',
                'image' => 'inspiration_motivation.jpg',
                'category_description' => 'Inspire and motivate your loved ones with encouraging words.',
                'seo_description' => 'Explore letters that provide strength, guidance, and motivation.',
                'status' => 1,
            ],
            [
                'category_name' => 'Customizable Letters',
                'slug' => 'customizable-letters',
                'icon' => 'custom_icon.png',
                'image' => 'customizable.jpg',
                'category_description' => 'Create personalized letters for any occasion with our customizable options.',
                'seo_description' => 'Design your own letters with unique themes and personal touches.',
                'status' => 1,
            ],

            [
                'category_name' => 'Long-Distance Love Letters',
                'slug' => 'long-distance-love-letters',
                'icon' => 'long_distance_icon.png',
                'image' => 'long_distance_love.jpg',
                'category_description' => 'Bridge the gap with heartfelt letters to keep the love alive across the miles.',
                'seo_description' => 'Send love letters designed to comfort and connect long-distance relationships.',
                'status' => 1,
            ],
            [
                'category_name' => 'Proposal Letters',
                'slug' => 'proposal-letters',
                'icon' => 'proposal_icon.png',
                'image' => 'proposal.jpg',
                'category_description' => 'Craft the perfect proposal with a letter that speaks from the heart.',
                'seo_description' => 'Romantic proposal letters to ask the biggest question of your life.',
                'status' => 1,
            ],
            [
                'category_name' => 'Secret Admirer Letters',
                'slug' => 'secret-admirer-letters',
                'icon' => 'secret_admirer_icon.png',
                'image' => 'secret_admirer.jpg',
                'category_description' => 'Reveal your feelings anonymously with a touch of mystery and romance.',
                'seo_description' => 'Send a secret admirer note to the one who has captured your heart.',
                'status' => 1,
            ],
            [
                'category_name' => 'Anniversary Love Letters',
                'slug' => 'anniversary-love-letters',
                'icon' => 'anniversary_icon.png',
                'image' => 'anniversary_love.jpg',
                'category_description' => 'Celebrate the journey of love with beautiful anniversary letters.',
                'seo_description' => 'Mark your special day with words that honor your love story.',
                'status' => 1,
            ],
            [
                'category_name' => 'Letters for New Relationships',
                'slug' => 'new-relationship-letters',
                'icon' => 'new_relationship_icon.png',
                'image' => 'new_relationship.jpg',
                'category_description' => 'Nurture new love with letters that express excitement and affection.',
                'seo_description' => 'Share your budding feelings with letters perfect for new relationships.',
                'status' => 1,
            ],
            [
                'category_name' => 'Letters for Tough Times',
                'slug' => 'letters-for-tough-times',
                'icon' => 'tough_times_icon.png',
                'image' => 'tough_times.jpg',
                'category_description' => 'Offer comfort and support with letters designed for challenging moments.',
                'seo_description' => 'Words of encouragement and love to help navigate difficult times.',
                'status' => 1,
            ],
            [
                'category_name' => 'Good Morning Letters',
                'slug' => 'good-morning-letters',
                'icon' => 'good_morning_icon.png',
                'image' => 'good_morning.jpg',
                'category_description' => 'Start the day with loving messages that brighten their morning.',
                'seo_description' => 'Good morning letters to fill their day with warmth and positivity.',
                'status' => 1,
            ],
            [
                'category_name' => 'Good Night Letters',
                'slug' => 'good-night-letters',
                'icon' => 'good_night_icon.png',
                'image' => 'good_night.jpg',
                'category_description' => 'End the day with sweet and comforting good night letters.',
                'seo_description' => 'Send good night messages that ensure sweet dreams and peaceful rest.',
                'status' => 1,
            ],
            [
                'category_name' => 'Letters of Apology',
                'slug' => 'letters-of-apology',
                'icon' => 'apology_icon.png',
                'image' => 'apology.jpg',
                'category_description' => 'Say sorry with sincerity through carefully crafted apology letters.',
                'seo_description' => 'Heartfelt letters to mend relationships and seek forgiveness.',
                'status' => 1,
            ],
            [
                'category_name' => 'Letters of Appreciation',
                'slug' => 'letters-of-appreciation',
                'icon' => 'appreciation_icon.png',
                'image' => 'appreciation.jpg',
                'category_description' => 'Show gratitude and appreciation with thoughtful and loving words.',
                'seo_description' => 'Send appreciation letters that convey deep gratitude and affection.',
                'status' => 1,
            ],
            [
                'category_name' => 'Memory & Nostalgia Letters',
                'slug' => 'memory-nostalgia-letters',
                'icon' => 'nostalgia_icon.png',
                'image' => 'memory_nostalgia.jpg',
                'category_description' => 'Relive cherished memories and shared moments with nostalgic letters.',
                'seo_description' => 'Send letters that take a trip down memory lane, celebrating your shared past.',
                'status' => 1,
            ],
            [
                'category_name' => 'Letters to Future Self',
                'slug' => 'letters-to-future-self',
                'icon' => 'future_self_icon.png',
                'image' => 'future_self.jpg',
                'category_description' => 'Write to your future self with hopes, dreams, and words of wisdom.',
                'seo_description' => 'Craft letters meant to be read years from now, capturing your present self.',
                'status' => 1,
            ],
            [
                'category_name' => 'Thank You Letters',
                'slug' => 'thank-you-letters',
                'icon' => 'thank_you_icon.png',
                'image' => 'thank_you.jpg',
                'category_description' => 'Express gratitude with heartfelt thank you letters for any occasion.',
                'seo_description' => 'Send thank you notes that convey your deepest appreciation and thanks.',
                'status' => 1,
            ],
            [
                'category_name' => 'Letters of Encouragement',
                'slug' => 'letters-of-encouragement',
                'icon' => 'encouragement_icon.png',
                'image' => 'encouragement.jpg',
                'category_description' => 'Lift spirits and inspire with letters of encouragement and support.',
                'seo_description' => 'Encourage and motivate your loved ones with uplifting messages.',
                'status' => 1,
            ],
            [
                'category_name' => 'Rekindling Love Letters',
                'slug' => 'rekindling-love-letters',
                'icon' => 'rekindle_icon.png',
                'image' => 'rekindling_love.jpg',
                'category_description' => 'Revive the spark in your relationship with letters to rekindle love.',
                'seo_description' => 'Letters designed to reignite passion and deepen your connection.',
                'status' => 1,
            ],
        ];

        DB::table('templete_categories')->insert($categories);

    }
}
